language: node_js
node_js: 9.9
addons:
  firefox: latest-esr
  apt:
    packages:
    - dbus-x11
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  slack: txuniverse:O1XW4GuJH91iHr71md4n7rsl
deploy:
  skip_cleanup: true
  provider: heroku
  app: tx-base-website
  api_key: NU7sgA0Zgzz1xZMEbSb0k6iaBH8LqpOlQu+vMmnjaAKGu5XlKdOp4lNNWIMcNmH19Jl+T9efQsv6MeBIMfWGXQT2vNaeIYFfNz/Is12Phg7bv7vZ8mrgvCZOETSsNvWVql3HDvHGfc3gMmc9+gTyVHO8CsY+EdxVH5VdAVxzpVznGvV+OUaRRuYXwsY+NrUd4xRDYas48i7+JMEvq1RZA6Zz4vAJOk2siKW20zLN3g0CFCA9/mJ9Y8xDKFcT0aypJ16ZPKDMFYDgN9Hx244Sz/V3Y1t0zDTaeDou1Kg6Srq8JBjkJV25TXnlJijsSeyZx97PwzZYNxkDrUCxjpOmIbR4bCBgML+2ih5w7X55UyiG90mwvrfZqHoBQ0keMY8EVdUXGNpC9SVYRAh8GCWUgQh+wimGc8AvX8TtW8N9Ea5aLJTZOvFuqZgfQVRebldtRaqNl1hBAh/R+6D8moU9zPc31yunVM3IAcJcJRIk9wOBVRT61bPmZ8DPW3vkDjy6TT/6b7xfRwvqAyMiLxUvlnRQuyuMZ/KafoEPl6ogz7Z8jjcB+C96xGvdH8WlnfqG7sCK8pAB1NoXw20jbd/HC4KBcB5eDaWGTnGUfZZi8o3v31ucSGqDLN+2uDiUcWiZ2SYs010e0MeFa1T6gosFzVus+G7Mi8ERfaNOZLnDdP4=
before_deploy:
- git config --global user.email "me@example.com"
- git config --global user.name "deploy bot"
- node build
- git add dist/ --force
- git commit -m "Updating build."
