language: node_js
node_js: 7.3
addons:
  firefox: latest-esr
  apt:
    packages:
      - dbus-x11
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
notifications:
  slack: 'txuniverse:O1XW4GuJH91iHr71md4n7rsl'
deploy:
  skip_cleanup: true
  provider: heroku
  app: tx-base-website
  api_key: >-
    E4MesS4cwhccYwIdZIfuHjA6N0oB4ug/oAsuVk8rK/s5HHs9HHDBKzBiErNdbBhVANCtcc1Ec5k6lFCMToCwYHPsSL7Xd8HLIsX41HsBdy8RNpxenphJow/IQDHMoRdarwqZU7De8+W11oHafV1Igsq0uLl6xMKBnrRtYtt7J20gzTKWp7oXuhVCNiSxiad98mz1Dshw6qVePk784MB2P498ztpYej1ZFk7BPc2tzNivnU5/UrFkN1HC5Q928iuuu3IOkVCf3o6dvpUvcqRcYlm+WX4UaYMI+1X38fdFXaCYgTGKopIfOx1IEz+t6mU+ZGVYsdk1F27eARjjN4AFutxRd/+itzk+oSTXUAlyqisQmGb798DG3hYwmAwYMYkisTie44LW5V/S1k+hah46tKmCqQRQREcTCRe96mFb0kLkby3jX7FtRHwxX2CCGS/RsdD4hFnpTt/qthdGfTl35yaOlF44m8EjxGY8+yzPjHJqfBGuntvtcuA7TVT617+ExSy86B/0dlenxqglQ7u6YyjOymK0Ug9zXCKCRA9utytnttpY6A8EpleuJln385EpOiIqHgnxcmdKj2gm5OiNxBMdpfudQc3O5dLTDi9L2NNdFeJnFikG0K1CPvg/XsIBjzmJjWDn2YrSnOUfBxojg0TJQFIY8nUjw+BWGS4PaZo=
before_deploy:
  - git config --global user.email "me@example.com"
  - git config --global user.name "deploy bot"
  - node build
  - git add dist/ --force
  - git commit -m "Updating build."
  - 'npm run deploy:ci'
env:
  global:
    - secure: >-
        aKjfLW/cY5UkbzEhFAA4TeM6aNe9Vx2XjP9BjoajbXbDGK5TWiXkBGDAX0GW2nM/3p0ckODRITK4q3KVrwIwnc7haDwrEvp8j284GvU8pwySRbPJiMElzNHlV1gLGnDGADxhSi+8Dwv0TTqd0j5ts5kDhCwr7dXAj6NmMRDnYKz0NDGHifbFZ4c6B/m+lwTiNA2i+reIhnfHvns4nrfF4yCMT52tY4JS5PcZkTYJndLHp9/7bxQ1ZONMediy90XTp73GSA6U3+XxMYHCi1d7MiNYM5j9COH2CwwDq/J2ZNNKOf7pQNE8Qiac8IIl5DGuT+yHbOgZnWNultGVQVBxJX0KlchRjJlxB+0C36/PRB2R5ZulMQQJSQ8ZhpbNQnAtLP2dbP3unENprdbp38PlECL6j4alz0YgGFiyfGj+dnE/MvCvJ72f24k8ZjmdxRMBGAIs9LSxXqrBn7i1WNVtrdw+L98hnCIntsmGcEkNtAQdQ64XMKh1hgBjF0Lkb19TGclJxFO+/0S+2pQ9VHeWLREqUuyFK3NzcfIj1Vd/wTA55abaqGM2oOVHEmkEOoHzuzNDA9GMNlmIgwf/QB7KqB6kBb6exPecdELWHG66iiR9FA8K3mWkucXx/A6g8odeRi8bbYrXyKJeRSmqNGMSQ/H6yHjII1x4ZK481TsSuT4=
