language: node_js
node_js: 9.9
addons:
  firefox: latest-esr
  apt:
    packages:
    - dbus-x11
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  skip_cleanup: true
  provider: heroku
  app: accesswebwatcher-website
  api_key:
    secure: NEWXfFW7HAv76k7hrbCYMrFG0kkWMbfrL8Aq7nfCwxjR0pAZQusFq3UiTk4fBgO363fu86gO+vTC5mPCmLP9Msm1hESfBPV3jGyAlCunlA5NwoGdAUSA5wdCodmsks+ZJq/mhTBOUE2lvNqdHRyNZiea7vhhA5d7ZcWgW2t8q7o1FLe3esnd0RXGMlumWkkubKEBMv0FSGg3GXP5lkRVYN0ANVDUEqUQYTbmmvenvClwsrsCkK/N0O3ajlRfvCEXdtQJFFvRTmXD/mfzDEEn99KWLTtRQU0BV7hwwJO3oMMctCkr5d6pNYJyJc69N+f+sVZmpn6lRqR3iRw/FUQ0wyLKXFGNLuzgDiUFi7mwowfQqYQjibCKSS4WSukWYuZ6rwVwyBzLoqdMrBJG49vqUgXcnWg820KAkWOpz8wiSYnEkIkvE/8x7IpBGzkHscD/Y5L7PJ1PD+Lvyf+99MXvsRM8khsZ1lGGfxfcGbJRXXTgtDUCVxDuffyR51T9+hLd78ooi5nSveO3vHQyV8zl+i7cxVcCjW7K9b7M02/Axg7DmYcrENN1HShMLz5JvrIqWO0Jylqg4pI7Whvs71qCQpE2kue2ksaXfXF69wWeYn5myCTpJfMrI9wsMxUzSiX5O1UbLHiCTzD8HzKAVVIDXY2hnePpKeohavFnvdAmeZ8=
before_deploy:
- git config --global user.email "me@example.com"
- git config --global user.name "deploy bot"
- node build
- git add dist/ --force
- git commit -m "Updating build."